/* Generated by wbuild from "MenuBar.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfMenuBar_H_
#define _XfwfMenuBar_H_
#include <Xfwf/Rows.h>
Boolean  XfwfCallProcessMenu(
Widget,Widget ,Cursor 
);
typedef struct _XfwfMenuBarClassRec *XfwfMenuBarWidgetClass;
typedef struct _XfwfMenuBarRec *XfwfMenuBarWidget;
externalref WidgetClass xfwfMenuBarWidgetClass;
#endif /*_XfwfMenuBar_H_*/
