/* Generated by wbuild from "OptButton.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfOptionButton_H_
#define _XfwfOptionButton_H_
#include <Xfwf/PullDown.h>
typedef struct _XfwfOptionButtonClassRec *XfwfOptionButtonWidgetClass;
typedef struct _XfwfOptionButtonRec *XfwfOptionButtonWidget;
externalref WidgetClass xfwfOptionButtonWidgetClass;
#endif /*_XfwfOptionButton_H_*/
