#
#   Makefile definitions for cdoc
#
OBJ   = getfiles.o getopt.o add_html_toc.o
PROG  = cdoc add_html_toc
MANP  = cdoc.m
CINCL = cdoc.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

