#
#   Makefile definitions for contour
#
OBJ   = contour.o
PROG  = contour
MANP  = contour.m
CINCL =  contour.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

