#
#   Makefile definitions for combine
#
OBJ   = combine.o
PROG  = combine
MANP  = combine.m
CINCL =  combine.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

