#
#   Makefile definitions for fwf/Dir
#
FWFOBJ  = RegExp.o Directory.o DirMgr.o
FWFINCL = RegExp.i Directory.i DirMgr.i

include:fwfincl
object: fwfobj
lib:    fwflib
dso:    fwf_dso
program:
doc:    
xprog:  
