/* Generated by wbuild from "Button.w"
** (generator version $Revision$ of $Date$)
*/
#include <xite/includes.h>
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#include <Xfwf/ButtonP.h>
#line 60 "Button.w"
static void activate(
Widget,XEvent*,String*,Cardinal*
);

static XtActionsRec actionsList[] = {
{"activate", activate},
};

static char defaultTranslations[] = "\
<Btn1Down>: set_shadow(sunken) \n\
<Btn1Down>,<Btn1Up>: activate() set_shadow() \n\
Button1<Leave>: set_shadow() \n\
<Key>Return: set_shadow(sunken) activate() set_shadow() \n\
";
static void _resolve_inheritance(
WidgetClass
);

static XtResource resources[] = {
#line 31 "Button.w"
{XtNactivate,XtCActivate,XtRCallback,sizeof(((XfwfButtonRec*)NULL)->xfwfButton.activate),XtOffsetOf(XfwfButtonRec,xfwfButton.activate),XtRImmediate,(XtPointer)NULL },
#line 35 "Button.w"
{XtNframeWidth,XtCFrameWidth,XtRDimension,sizeof(((XfwfButtonRec*)NULL)->xfwfFrame.frameWidth),XtOffsetOf(XfwfButtonRec,xfwfFrame.frameWidth),XtRImmediate,(XtPointer)2 },
#line 40 "Button.w"
{XtNtraversalOn,XtCTraversalOn,XtRBoolean,sizeof(((XfwfButtonRec*)NULL)->xfwfCommon.traversalOn),XtOffsetOf(XfwfButtonRec,xfwfCommon.traversalOn),XtRImmediate,(XtPointer)True },
};

XfwfButtonClassRec xfwfButtonClassRec = {
{ /* core_class part */
(WidgetClass) &xfwfLabelClassRec,
"XfwfButton",
sizeof(XfwfButtonRec),
NULL,
_resolve_inheritance,
FALSE,
NULL,
NULL,
XtInheritRealize,
actionsList,
1,
resources,
3,
NULLQUARK,
True ,
XtExposeCompressMultiple ,
True ,
False ,
NULL,
XtInheritResize,
XtInheritExpose,
NULL,
NULL,
XtInheritSetValuesAlmost,
NULL,
XtInheritAcceptFocus,
XtVersion,
NULL,
defaultTranslations,
XtInheritQueryGeometry,
XtInheritDisplayAccelerator,
NULL 
},
{ /* composite_class part */
XtInheritGeometryManager,
XtInheritChangeManaged,
XtInheritInsertChild,
XtInheritDeleteChild,
NULL
},
{ /* XfwfCommon_class part */
XtInherit_compute_inside,
XtInherit_total_frame_width,
XtInherit_highlight_border,
XtInherit_unhighlight_border,
XtInherit_would_accept_focus,
XtInherit_traverse,
XtInherit_lighter_color,
XtInherit_darker_color,
NULL ,
},
{ /* XfwfFrame_class part */
0
},
{ /* XfwfBoard_class part */
XtInherit_set_abs_location,
},
{ /* XfwfLabel_class part */
XtInherit_set_label,
},
{ /* XfwfButton_class part */
0
},
};
WidgetClass xfwfButtonWidgetClass = (WidgetClass) &xfwfButtonClassRec;
/*ARGSUSED*/
#line 60 "Button.w"
static void activate(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    XtCallCallbackList(self, ((XfwfButtonWidget)self)->xfwfButton.activate, event);
}

static void _resolve_inheritance(class)
WidgetClass class;
{
  XfwfButtonWidgetClass c = (XfwfButtonWidgetClass) class;
  XfwfButtonWidgetClass super;
  static CompositeClassExtensionRec extension_rec = {
    NULL, NULLQUARK, XtCompositeExtensionVersion,
    sizeof(CompositeClassExtensionRec), True};
  CompositeClassExtensionRec *ext;
  ext = (CompositeClassExtensionRec *)XtMalloc(sizeof(*ext));
  *ext = extension_rec;
  ext->next_extension = c->composite_class.extension;
  c->composite_class.extension = (XtPointer)ext;
  if (class == xfwfButtonWidgetClass) return;
  super = (XfwfButtonWidgetClass)class->core_class.superclass;
}
