#
#   Makefile definitions for fwf/Button
#
FWFOBJ  = Button.o
FWFINCL = Button.i ButtonP.i
ROFF3   = XfwfButton.man

include:fwfincl
object: fwfobj
lib:    fwflib
dso:    fwf_dso
program:
doc:    roff3
xprog:  
