/* Generated by wbuild from "TextMenu.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfTextMenuP_H_
#define _XfwfTextMenuP_H_
#include <xite/includes.h>
#include <X11/ShellP.h>
#include <Xfwf/TextMenu.h>

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfTextMenuClassPart;

typedef struct _XfwfTextMenuClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
ShellClassPart shell_class;
OverrideShellClassPart overrideShell_class;
XfwfTextMenuClassPart xfwfTextMenu_class;
} XfwfTextMenuClassRec;

typedef struct {
/* resources */
XFontStruct * font;
Pixel  foreground;
String  tablist;
String  menu;
long  active;
int  selection;
Cursor  cursor;
XtCallbackList  activate;
XtCallbackList  changeSelection;
/* private state */
Cardinal  nitems;
char * shortcut;
Position * offset;
String * item;
Position * line;
GC  gc;
GC  rvgc;
GC  graygc;
int * tabs;
int  itemheight;
} XfwfTextMenuPart;

typedef struct _XfwfTextMenuRec {
CorePart core;
CompositePart composite;
ShellPart shell;
OverrideShellPart overrideShell;
XfwfTextMenuPart xfwfTextMenu;
} XfwfTextMenuRec;

externalref XfwfTextMenuClassRec xfwfTextMenuClassRec;

#endif /* _XfwfTextMenuP_H_ */
