/* Generated by wbuild from "Toggle.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfToggleP_H_
#define _XfwfToggleP_H_
#include <Xfwf/ButtonP.h>
#include <Xfwf/Toggle.h>

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfToggleClassPart;

typedef struct _XfwfToggleClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfLabelClassPart xfwfLabel_class;
XfwfButtonClassPart xfwfButton_class;
XfwfToggleClassPart xfwfToggle_class;
} XfwfToggleClassRec;

typedef struct {
/* resources */
XtCallbackList  onCallback;
XtCallbackList  offCallback;
Boolean  on;
#ifndef NO_XPM
Icon * onIcon;
Icon * offIcon;
#endif
/* private state */
GC  on_gc;
GC  off_gc;
Dimension  saveLeftMargin;
} XfwfTogglePart;

typedef struct _XfwfToggleRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfLabelPart xfwfLabel;
XfwfButtonPart xfwfButton;
XfwfTogglePart xfwfToggle;
} XfwfToggleRec;

externalref XfwfToggleClassRec xfwfToggleClassRec;

#endif /* _XfwfToggleP_H_ */
