#
#   Makefile definitions for fht - fast hartley transform
#
OBJ   = fht2d.o ht2ft.o ft2ht.o fhtPower.o fhtPhase.o
PROG  = fht2d ht2ft ft2ht fhtPower fhtPhase
MANP  = fht2d.m ht2ft.m ft2ht.m fhtPower.m fhtPhase.m
CINCL =  fht.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

