#!/bin/sh

# $Id$

echo "" 1>&2

if test "$confirm" -eq 1
then
  echo    "Do you want to continue (building library, executables," 1>&2
  $echoNl "manual documentation and hypertext documentation)? ([y]/n) " 1>&2

  read continue
else
  continue="y"
fi

if test -z "$continue" -o "$continue" = "y" -o "$continue" = "Y" -o \
  "$continue" = "yes" -o "$continue" = "YES" -o "$continue" = "Yes"
then
  exit 0
else
  exit 1
fi
