#!/bin/sh

# $Id$

########## Confirm parameters ##########

echo "" 1>&2
echo "The following information has been determined (and has been saved" 1>&2
echo "to the file $paramOutFile):" 1>&2
if test "$buildOnly" -eq 0
then
	echo "tarfile         : $ztarfile" 1>&2
else
	echo "tarfile         : Not used for a rebuild only." 1>&2
fi
echo "XITE_HOSTTYPE   : $XITE_HOSTTYPE" 1>&2
echo "XITE_HOME       : $XITE_HOME" 1>&2
echo "XITE_BIN_DEST   : $XITE_BIN_DEST" 1>&2
echo "XITE_LIB_DEST   : $XITE_LIB_DEST" 1>&2
echo "XITE_INC_DEST   : $XITE_INC_DEST" 1>&2
echo "XITE_MAN_DEST   : $XITE_MAN_DEST" 1>&2
echo "XITE_DOC_DEST   : $XITE_DOC_DEST" 1>&2
echo "X_INC_DIR       : $X_INC_DIR" 1>&2
echo "X_LIB_DIR       : $X_LIB_DIR" 1>&2
if test "$tiff_install" = "y"
then
  echo "TIFF_INC_DIR    : $TIFF_INC_DIR" 1>&2
  echo "TIFF_LIB_DIR    : $TIFF_LIB_DIR" 1>&2
fi
if test "$pnm_install" = "y"
then
  echo "PNM_INC_DIR     : $PNM_INC_DIR" 1>&2
  echo "PNM_LIB_DIR     : $PNM_LIB_DIR" 1>&2
fi
if test "$matlab_install" = "y"
then
  echo "MATLAB_LIB      : $MATLAB_LIB" 1>&2
  echo "MATLAB_INC      : $MATLAB_INC" 1>&2
  echo "MATLAB_MEX_DEST : $MATLAB_MEX_DEST" 1>&2
fi
echo "CC              : $CC" 1>&2

if test "$confirm" -eq 1
then
  echo "" 1>&2
  $echoNl "Do you wish to continue? ([y]/n) " 1>&2
  read ok
else
  ok="y"
fi

if test "$ok" != "" -a "$ok" != "y" -a "$ok" != "Y" -a "$ok" != "yes" -a "$ok" != "YES"
then
  echo "" 1>&2
  echo "XITE installation/build aborted." 1>&2
  echo "" 1>&2
  $paramMessage 1>&2
  # No cleaning necessary (except $TMPDIR)
  echo "exit 1"
  exit 1
fi
