#!/bin/sh

# $Id$

# Determine whether to include <dirent.h>

if [ "$XITE_HOSTTYPE" = "SunOS5" -o "$XITE_HOSTTYPE" = "NT4" ]; then
	dirent="-DNO_DIRENT"
else
	dirent=""
fi

echo "dirent=$dirent"
echo "export dirent"
