#!/bin/sh

# $Id$

# Determine what kind of regex interface to use

if test -f /usr/include/regex.h
then
  regex="-DREGEX"
elif test ! -f /usr/include/regexp.h
then
  regex="-DNO_REGEXP"
else
  regex=""
fi

echo "regex=$regex"
echo "export regex"
