#!/bin/sh

# $Id$

if test "$quiet" -eq 0
then
echo "Editing xite_cshrc." 1>&2
fi

if test "$buildOnly" -eq 0
then
  if test -f xite_cshrc
  then
    echo "Moving existing xite_cshrc to xite_cshrc.old." 1>&2
    mv xite_cshrc xite_cshrc.old
  fi

  awk -f $edcshrc bin=$XITE_BIN_DEST man=$XITE_MAN_DEST \
    doc=$XITE_DOC_DEST home=$XITE_HOME \
    xite_hosttype=$XITE_HOSTTYPE \
    xite_cshrc.tmpl > xite_cshrc
else
  if test -f xite_cshrc
  then
    echo "Backup copy of existing xite_cshrc put in xite_cshrc.bak." 1>&2
    cp xite_cshrc xite_cshrc.bak
  fi

  if test -s xite_cshrc.bak
  then
    infile=xite_cshrc.bak
  else
    infile=xite_cshrc.tmpl
  fi

  awk -f $edcshrc bin=$XITE_BIN_DEST man=$XITE_MAN_DEST \
    doc=$XITE_DOC_DEST home=$XITE_HOME \
    home=$XITE_HOME xite_hosttype=$XITE_HOSTTYPE \
    $infile > xite_cshrc
fi

if test $? -ne 0
then
  echo "ERROR:" 1>&2
  echo "Editing xite_cshrc failed." 1>&2
  echo "" 1>&2
  $paramMessage 1>&2

  exit 1
fi

exit 0
