#!/bin/sh

# $Id$

if test -n "$1"
then
  fileName="$1"
else
  fileName='the parameter save file'
fi

cat <<EOF
You can avoid retyping the necessary parameters when you restart
this script, by using the option -f to read parameters from
$fileName. Get help by doing 'sh install_xite -h'.
EOF
