#!/bin/sh

# $Id$
# Takes one argument, the suggested platform name.

XITE_HOSTTYPE=`expr "$1" : '[ ]*\(.*\)'`

if test "$XITE_HOSTTYPE" != "AIX" \
     -a "$XITE_HOSTTYPE" != "IRIX" \
     -a "$XITE_HOSTTYPE" != "IRIX64" \
     -a "$XITE_HOSTTYPE" != "Linux" \
     -a "$XITE_HOSTTYPE" != "OSF1" \
     -a "$XITE_HOSTTYPE" != "SunOS5" \
     -a "$XITE_HOSTTYPE" != "SunOS" \
     -a "$XITE_HOSTTYPE" != "NT4" \
     -a "$XITE_HOSTTYPE" != "CYGWIN32" \
     -a "$XITE_HOSTTYPE" != "Other"
then
    exit 1
else
    exit 0
fi
