#
#   Makefile definitions for gradInv
#
OBJ   = gradInv.o
PROG  = gradInv
MANP  = gradInv.m
CINCL =  gradInv.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

