/* Generated by wbuild from "OptButton.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfOptionButtonP_H_
#define _XfwfOptionButtonP_H_
#include <Xfwf/PullDownP.h>
#include <Xfwf/OptButton.h>

typedef struct {
/* methods */
/* class variables */
int dummy;
} XfwfOptionButtonClassPart;

typedef struct _XfwfOptionButtonClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
XfwfCommonClassPart xfwfCommon_class;
XfwfFrameClassPart xfwfFrame_class;
XfwfBoardClassPart xfwfBoard_class;
XfwfLabelClassPart xfwfLabel_class;
XfwfButtonClassPart xfwfButton_class;
XfwfPullDownClassPart xfwfPullDown_class;
XfwfOptionButtonClassPart xfwfOptionButton_class;
} XfwfOptionButtonClassRec;

typedef struct {
/* resources */
/* private state */
int dummy;
} XfwfOptionButtonPart;

typedef struct _XfwfOptionButtonRec {
CorePart core;
CompositePart composite;
XfwfCommonPart xfwfCommon;
XfwfFramePart xfwfFrame;
XfwfBoardPart xfwfBoard;
XfwfLabelPart xfwfLabel;
XfwfButtonPart xfwfButton;
XfwfPullDownPart xfwfPullDown;
XfwfOptionButtonPart xfwfOptionButton;
} XfwfOptionButtonRec;

externalref XfwfOptionButtonClassRec xfwfOptionButtonClassRec;

#endif /* _XfwfOptionButtonP_H_ */
