#
#   Makefile definitions for fwf/Toggle
#
FWFOBJ  = Toggle.o
FWFINCL = Toggle.i ToggleP.i
ROFF3   = XfwfToggle.man

include:fwfincl
object: fwfobj
lib:    fwflib
dso:    fwf_dso
program:
doc:    roff3
xprog:  
