#
#   Makefile definitions for fwf/Prompt
#
FWFOBJ  = Prompt.o
FWFINCL = Prompt.i PromptP.i
ROFF3   = XfwfPrompt.man

include:fwfincl
object: fwfobj
lib:    fwflib
dso:    fwf_dso
program:
doc:    roff3
xprog:  
