#
#   Makefile definitions for principal
#
OBJ   = linearTrans.o
PROG  = linearTrans
MANP  = linearTrans.m
CINCL =  principal.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

