#
#   Makefile definitions for fwf/Common
#
FWFOBJ  = Common.o
FWFINCL = Common.i CommonP.i
ROFF3   = XfwfCommon.man

include:fwfincl
object: fwfobj
lib:    fwflib
dso:    fwf_dso
program:
doc:    roff3
xprog:  
