#
#   Makefile definitions for sigma
#
OBJ   = sigma.o
PROG  = sigma
MANP  = sigma.m
CINCL =  sigma.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

