#
#   Makefile definitions for dither
#
OBJ   = dither.o
PROG  = dither
MANP  = dither.m
CINCL =  dither.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

