#
#   Makefile definitions for fwf/Board
#
FWFOBJ  = Board.o
FWFINCL = Board.i BoardP.i
ROFF3   = XfwfBoard.man

include:fwfincl
object: fwfobj
lib:    fwflib
dso:    fwf_dso
program:
doc:    roff3
xprog:  
