#
#   Makefile definitions for kncn
#
OBJ   = kncn.o mbkncn.o
PROG  = kncn mbkncn
MANP  = kncn.m mbkncn.m
CINCL =  kncn.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

