#
#   Makefile definitions for convert

OBJ     = biffConvert.o ascii2biff.o pseudo2rgb.o biff2raw.o biff2ascii.o \
	  biffswap.o
PROG    = biffConvert raw2biff ascii2biff pseudo2rgb biff2raw biff2ascii \
	  biffswap
MANP    = biffConvert.m raw2biff.m ascii2biff.m pseudo2rgb.m biff2raw.m \
	  biff2ascii.m biffswap.m
CINCL   = convert.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

