#
#   Makefile definitions for the canny subdirectory
#
OBJ   = canny.o
PROG  = canny
MANP  = canny.m
CINCL = canny.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

