/* Generated by wbuild from "Button.w"
** (generator version $Revision$ of $Date$)
*/
#ifndef _XfwfButton_H_
#define _XfwfButton_H_
#include <Xfwf/Label.h>
#ifndef XtNactivate
#define XtNactivate "activate"
#endif
#ifndef XtCActivate
#define XtCActivate "Activate"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

typedef struct _XfwfButtonClassRec *XfwfButtonWidgetClass;
typedef struct _XfwfButtonRec *XfwfButtonWidget;
externalref WidgetClass xfwfButtonWidgetClass;
#endif /*_XfwfButton_H_*/
