#!/bin/sh

# This is where install_xite will place its output
export XITE_HOME=`pwd`
export XITE_HOME_DEST=/usr/local/xite_3.4.4
export XITE_LIB=$XITE_HOME_DEST/lib

# Matlab home directory
export MATLAB=/usr/local/matlab6p5

# Prepare xite.tar with filenames without leading <package>-<version> path
#rm -f ../xite.tar
#tar cf ../xite.tar *

# install_xite will not run when some installation directories are missing
mkdir -p $XITE_HOME_DEST
mkdir -p $XITE_HOME_DEST/bin
mkdir -p $XITE_LIB
mkdir -p $XITE_HOME_DEST/include/xite
mkdir -p $XITE_HOME_DEST/man
mkdir -p $XITE_HOME_DEST/doc/xite

./install_xite -x $XITE_HOME -b $XITE_HOME_DEST/bin -l $XITE_LIB \
	-i $XITE_HOME_DEST/include \
	-m $XITE_HOME_DEST/man -e $XITE_HOME_DEST/doc/xite \
	-xi /usr/include -xl /usr/lib32 \
	-ti /usr/include -tl /usr/lib32 \
	-pi /usr/freeware/include -pl /usr/freeware/lib32 \
	-mh $MATLAB -mi $MATLAB/extern/include -ml $MATLAB/extern/lib/sgi \
	-mm $MATLAB/toolbox/local \
	-p IRIX -cc cc \
	-t ../xite.tar \
	-nomail \
	-s -c

# Compile the package
./install_xite -p IRIX -f xite_params -nomail -d -c

