#
# Makefile.def.in for all toolkit code
# The use of the following code requires:
#  (a) definition of srcdir
#  (b) definition of VPATH without using any Makefile variables (optional)
#  (c) definition of LOCALDEFS an LOCALDEBUG (optional)
#

AM_CPPFLAGS = -I. -I$(srcdir) -I$(top_srcdir)/include -I$(configdir)/include $(LOCALINCLUDES)

SUFFIXES = .m

.c.1:
	-rm -rf ttman
	mkdir -p ttman/man1 ttman/man3
	-@if test "$(@)" != "_MANP_"; then \
	  echo $(top_builddir)/src/cdoc/cdoc -t \
	  `grep "^#\{0,1\}\/\*[PFD]:" $< |\
	  sed 's/^#\{0,1\}../-e /' |\
	  sed 's/.[        ]*$$//' |\
	  sed 's/=.*//' ` $< ttman/ ; \
	  $(top_builddir)/src/cdoc/cdoc -t \
	  `grep "^#\{0,1\}\/\*[PFD]:" $< |\
	  sed 's/^#\{0,1\}../-e /' |\
	  sed 's/.[        ]*$$//' |\
	  sed 's/=.*//' ` $< ttman/ ; \
	  echo mv ttman/man?/* . ; \
	  mv ttman/man?/* . ; \
	fi
	-rm -rf ttman

.sh.1:
	-rm -rf ttman
	mkdir -p ttman/man1 ttman/man3
	-@if test "$(@)" != "_MANP_"; then \
	  echo $(top_builddir)/src/cdoc/cdoc -t \
	  -s '*.sh' \
	  `grep "^#\{0,1\}\/\*[PFD]:" $< |\
	  sed 's/^#\{0,1\}../-e /' |\
	  sed 's/.[        ]*$$//' |\
	  sed 's/=.*//' ` $< ttman/ ; \
	  $(top_builddir)/src/cdoc/cdoc -t \
	  -s '*.sh' \
	  `grep "^#\{0,1\}\/\*[PFD]:" $< |\
	  sed 's/^#\{0,1\}../-e /' |\
	  sed 's/.[        ]*$$//' |\
	  sed 's/=.*//' ` $< ttman/ ; \
	  echo mv ttman/man?/* . ; \
	  mv ttman/man?/* . ; \
	fi
	-rm -rf ttman
