#
#   Makefile definitions for draw - drawing routines and programs
#
OBJ   = mkImg.o bdf2biff.o
PROG  = mkImg bdf2biff biffwrite
MANP  = mkImg.m bdf2biff.m biffwrite.m
CINCL  = draw.i

include:cincl
object: cobj
lib:    clib
dso:    xite_dso
program:cprog
doc:    manpage
xprog:  

