#
#   Makefile definitions for fwf/PullDown
#
FWFOBJ  = PullDown.o
FWFINCL = PullDown.i PullDownP.i
ROFF3   = XfwfPullDown.man

include:fwfincl
object: fwfobj
lib:    fwflib
dso:    fwf_dso
program:
doc:    roff3
xprog:  
